### ISSUE TITLE
Requests: Notifications, disable scrollbar, make a tray icon

### ISSUE THREAD

**Issue by markubiak** [jtervay97/Desktop-SMS-Client#1]
This is for Linux, I can't confirm or deny functionality on Windows.  This app is working very well for me so far.  It seems like, after it starts, it keeps running in the background.  However, at least on Linux, there's no tray icon to indicate this and if I close the app I have no way to reopen it.  Additionally, I always have a scrollbar on the right side.  No idea why, it doesn't scroll anything.  It looks like it's a part of Chromium, not part of Yappy.  Lastly, and probably most importantly, I don't get notifications for new texts!  No popup, nothing.  If you need any info or help, let me know, but just know that I don't know any NodeJS or even regular JS.

**Comment by jtervay97** [comment]
Hey there,

It does currently keep running in the background without a tray icon. I experience the same thing on Windows. I also have the scrollbar on the right.

This app was created using the Electron framework, and Electron does not currently support desktop notifications. However, there have been rare instances where I did receive popups, but I cannot replicate it reliably.

I will look into minimizing to icon tray & removing the scrollbar. Notifications will also be looked into, but until I can find a reliable way to replicate some rare behaviors, they are a relatively low priority, as they are not 'officially' supported in Electron apps. There are ways of displaying notifications, but they aren't quite the style of notifications that you might see from Pushbullet or the likes.

**Comment by markubiak** [comment]
I can tell you right now that notifications on Linux are done by libnotify. No idea for Windows though. Thanks!

**Comment by markubiak** [comment]
Just to add, there's also [this](https://developer.mozilla.org/en-US/docs/Web/API/notification), which is supposed to work with Electron.

**Comment by markubiak** [comment]
I'm gonna condense research about notifications to one post.  Windows provides no native way to show notifications, so I'm not sure what could be done there.  On Linux, applications plug into libnotify to send desktop notifications.  For example, navigate to a terminal and type `notify-send "Title" "Body" --icon=firefox`, which should give you a notification with the firefox icon.  [The Arch Linux Wiki page on libnotify](https://wiki.archlinux.org/index.php/Desktop_notifications#Usage_in_programming) has usage examples in dozens of programming languages, including Javascript, although it seems to require an external library.  There's also [HTML5 Desktop Notifications Library](https://github.com/ttsvetko/HTML5-Desktop-Notifications#html5-desktop-notifications), which works on Windows, but I am not entirely sure how it works or how to install it.

**Comment by jtervay97** [comment]
I will likely not be implementing libnotify, as it's pretty much solely linux.

Additionally this is quite literally the first lines of JavaScript i've ever written, so it's a learning experience :smile: Looking to keep it relatively simple for now but we'll get there.

Hoping to have some changes out within a couple days.

**Comment by markubiak** [comment]
Excellent, thanks for the update

**Comment by jtervay97** [comment]
Notifications in progress. Scrollbar, tray icon, & properly killing background process added in v0.2. Currently no minimize to tray (future update). Will open an issue for notifications and minimize to tray.

**Comment by markubiak** [comment]
Great update, thanks for the work!
